"use strict";
const fs = require("node:fs");
const path = require("node:path");

// createFakeExec(steps) -> exec function
//
// A scripted state machine standing in for the real `claude` CLI, so
// bench/tests/driver.test.js can drive runSession() with zero network calls
// and zero real model invocations. Implements the same {args, stdin, cwd}
// -> Promise<{stdout}> contract as the real executor (see driver.js's
// claudeCliExec -- the prompt travels via stdin, argv carries only fixed
// flag tokens): runSession() cannot tell the difference.
//
// `steps` is consumed strictly in call order -- one step per exec() call,
// whether that call is the interviewee/workflow turn or the sim-user turn.
// Each step is one of:
//   { text, usage?, sessionId?, writeSpec?, specContent? }
//     -- returns a canned claude-CLI-shaped JSON payload. `usage` omitted
//        entirely simulates the CLI JSON omitting usage (never fabricate:
//        the driver must record null, not a guess). `writeSpec` is a path
//        relative to the call's cwd (the sandbox workspace); when present
//        the fake writes that file (with `specContent`, or a default body)
//        before returning, simulating the workflow having produced an
//        artifact on this turn.
//   { error: "message" }
//     -- rejects the exec() call, simulating an executor failure.
//   a function ({ args, stdin, cwd }) => any
//     -- escape hatch for tests that need custom behavior per call.
//
// The returned function also exposes `.calls`, an array of every {args,
// stdin, cwd} it was invoked with, in order -- so tests can assert on
// exactly what the driver asked the executor to run (e.g. that the sim-user
// call carries --model, or that the first call's stdin prompt includes the
// harness preamble).
function createFakeExec(steps) {
  const script = Array.isArray(steps) ? steps.slice() : [];
  let cursor = 0;
  const calls = [];

  const fakeExec = async function fakeExec({ args, stdin, cwd }) {
    calls.push({ args, stdin, cwd });

    if (cursor >= script.length) {
      throw new Error(
        `fake-cli: exec() called more times (${cursor + 1}) than the script has steps (${script.length})`
      );
    }
    const step = script[cursor++];

    if (typeof step === "function") {
      return step({ args, stdin, cwd });
    }

    if (step && step.error) {
      throw new Error(step.error);
    }

    if (step && step.writeSpec) {
      const specPath = path.join(cwd, step.writeSpec);
      fs.mkdirSync(path.dirname(specPath), { recursive: true });
      fs.writeFileSync(specPath, step.specContent || "# Spec\n\nGenerated by fake-cli for a test run.\n");
    }

    const payload = {
      session_id: (step && step.sessionId) || "fake-session-1",
      result: step && typeof step.text === "string" ? step.text : "",
    };
    if (step && Object.prototype.hasOwnProperty.call(step, "usage")) {
      payload.usage = step.usage;
    }

    return { stdout: JSON.stringify(payload) };
  };

  fakeExec.calls = calls;
  return fakeExec;
}

module.exports = { createFakeExec };
